### ISSUE TITLE
Example and descriptions

### ISSUE THREAD

**Issue by Haris888** [ttucsc/star-esdm#1]
Dear developer, is it a step-by-step guide to install and run this software for the statistical downscaling of the GCMs data? It seems the current version is not completing and I am confused about the difference between STAR-ESDM (your earth'future preprint) and  ARRM developed here...
Could you please answer these questions? Thank you!

**Comment by ttucsc** [comment]
ARRM_V2 was the original name for the software.
The code is designed to run on a parallel processing system managed by SLURM.   
You'll want to modify setup_slurm_gridded_run.m to fit your SLURM system.  It generates the SLURM scripts needed to run.
A future release will contain more detailed instructions.
